services:
  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile.dev
    container_name: ojt-api-dev
    volumes:
      - ../api:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-api}
      DB_USERNAME: ${DB_USERNAME:-ryan}
      DB_PASSWORD: ${DB_PASSWORD:-ryan1234}

    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ojt-network-dev

  client:
    build:
      context: ..
      dockerfile: docker/client/Dockerfile.dev
    container_name: ojt-client-dev
    volumes:
      - ../client:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    networks:
      - ojt-network-dev

networks:
  ojt-network-dev:
    driver: bridge

